Repository nih-cfde/training-and-engagement, pull requests merged in 2020-10, with the labels that each got.

#205 cfdebot tutorial - add landing pg info, update PR steps
  docs/General-Tutorials/cfdebot_website_editing.md
  docs/images/github-branch-stable.png
  docs/images/github-new-branch.png
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: Oct-2020, fixes

#154 Training website style guide
  docs/.pages
  docs/CF-Tutorials/.pages
  docs/CF-Tutorials/index.md
  docs/CFDE-Internal-Training/.pages
  docs/CFDE-Internal-Training/MIME-type/.pages
  docs/CFDE-Internal-Training/MIME-type/Example_data_files.md
  docs/CFDE-Internal-Training/MIME-type/Intro_MIME_type.md
  docs/CFDE-Internal-Training/MIME-type/Multiple_file_MIME.md
  docs/CFDE-Internal-Training/MIME-type/Unexpected_behavior.md
  docs/CFDE-Internal-Training/MIME-type/file.md
  docs/CFDE-Internal-Training/MIME-type/index.md
  docs/CFDE-Internal-Training/MIME-type/mime_supplementary_files/KF_File_ID.csv
  docs/CFDE-Internal-Training/MIME-type/mime_supplementary_files/file_screencast.cast
  docs/CFDE-Internal-Training/MIME-type/mime_supplementary_files/mimetype_screencast.cast
  docs/CFDE-Internal-Training/MIME-type/mime_supplementary_files/siegfried_screencast.cast
  docs/CFDE-Internal-Training/MIME-type/mime_supplementary_files/xdg-mime_screencast.cast
  docs/CFDE-Internal-Training/MIME-type/mimetype.md
  docs/CFDE-Internal-Training/MIME-type/siegfried.md
  docs/CFDE-Internal-Training/MIME-type/xdg-utils.md
  docs/CFDE-Internal-Training/ProtectedBranch_HowTo.md
  docs/CFDE-Internal-Training/Website-Style-Guide/.pages
  docs/CFDE-Internal-Training/Website-Style-Guide/0index.md
  docs/CFDE-Internal-Training/Website-Style-Guide/1WebsiteNavStyle.md
  docs/CFDE-Internal-Training/Website-Style-Guide/2GenTutorialStyle.md
  docs/CFDE-Internal-Training/Website-Style-Guide/3TutorialComponents.md
  docs/CFDE-Internal-Training/Website-Style-Guide/4RecordingStyleGuide.md
  docs/CFDE-Internal-Training/Website-Style-Guide/5PangeoBinderGuide.md
  docs/CFDE-Internal-Training/Website-Style-Guide/6PracticeGithubRepos.md
  docs/CFDE-Internal-Training/Website-Style-Guide/tutorial_template_docs/TutorialTemplate.md
  docs/CFDE-Internal-Training/cfdebot_website_editing.md
  docs/CFDE-Internal-Training/index.md
  docs/General-Tutorials/.pages
  docs/General-Tutorials/index.md
Labels: new

#217 Edits to release plan: inclusion of release notes workflow and checklist explanation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/action-release-drafter.yml
  .github/workflows/comment_pr.yml
  docs/TrainingRepoReleasePlan/TrainingRepo-Release-Plan.md
  docs/images/Release_workflow_training_repo.png
  docs/images/Training_review_process.png
Labels: fixes

#137 Connecting to AWS on windows and running BLAST on AWS
  docs/Bioinformatics-Tutorials/.pages
  docs/Bioinformatics-Tutorials/BLAST-Command-Line/BLAST1.md
  docs/Bioinformatics-Tutorials/BLAST-Command-Line/BLAST2.md
  docs/Bioinformatics-Tutorials/BLAST-Command-Line/BLAST3.md
  docs/Bioinformatics-Tutorials/BLAST-Command-Line/BLAST4.md
  docs/Bioinformatics-Tutorials/index.md
  docs/General-Tutorials/.pages
  docs/General-Tutorials/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/General-Tutorials/Introduction_to_Amazon_Web_Services/introtoaws2.md
  docs/General-Tutorials/Introduction_to_Amazon_Web_Services/introtoaws3.md
  docs/General-Tutorials/Introduction_to_Amazon_Web_Services/introtoaws4.md
  docs/General-Tutorials/index.md
  docs/images/Mobaxterm_transfer1.PNG
  docs/images/Mobaxterm_transfer2.PNG
  docs/images/Terminate.png
  docs/images/aws_1.PNG
  docs/images/aws_10.png
  docs/images/aws_11.png
  docs/images/aws_12.PNG
  docs/images/aws_2.PNG
  docs/images/aws_3.png
  docs/images/aws_4.png
  docs/images/aws_5.png
  docs/images/aws_6.png
  docs/images/aws_7.png
  docs/images/aws_8.png
  docs/images/aws_9.PNG
  docs/images/mobaxterm_1.PNG
  docs/images/mobaxterm_2.PNG
  docs/images/mobaxterm_3.PNG
  docs/images/mobaxterm_3_2.PNG
  docs/images/mobaxterm_4.PNG
  mkdocs.yml
Labels: Oct-2020, new

#235 CFDE Portal Tutorial
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/manhattan.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_2.md
  docs/CF-Tutorials/.pages
  docs/CF-Tutorials/CFDE-Portal/.pages
  docs/CF-Tutorials/CFDE-Portal/Blood-Cancer/.pages
  docs/CF-Tutorials/CFDE-Portal/Blood-Cancer/blood-cancer-data-access.md
  docs/CF-Tutorials/CFDE-Portal/Blood-Cancer/blood-cancer-portal-export.md
  docs/CF-Tutorials/CFDE-Portal/Movement-Related-Disorders/.pages
  docs/CF-Tutorials/CFDE-Portal/Movement-Related-Disorders/movement-disorders-data-access.md
  docs/CF-Tutorials/CFDE-Portal/Movement-Related-Disorders/movement-disorders-portal-export.md
  docs/CF-Tutorials/CFDE-Portal/index.md
  docs/CF-Tutorials/index.md
  docs/CFDE-Internal-Training/MIME-type/siegfried.md
  docs/CFDE-Internal-Training/ProtectedBranch_HowTo.md
  docs/CFDE-Internal-Training/cfdebot_website_editing.md
  docs/CFDE-Internal-Training/index.md
  docs/General-Tutorials/Jekyll_Tutorial.md
  docs/General-Tutorials/mkdocs.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_3_KF_Registration.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_4_Cavatica_Registration.md
  docs/Resources/bash_cheatsheet.md
  docs/images/AML-anatomy-filter.png
  docs/images/AML-assay-anatomy.png
  docs/images/AML-blood-filter.png
  docs/images/AML-blood-subset.png
  docs/images/AML-cohort-export.png
  docs/images/AML-final-cohort.png
  docs/images/CFDE-portal-biosample.png
  docs/images/CFDE-portal-blood-cancer-export.png
  docs/images/CFDE-portal-collection.png
  docs/images/CFDE-portal-movement-disorder-export.png
  docs/images/GTEx-data-annotations.png
  docs/images/GTEx-data-download.png
  docs/images/GTEx-login-page.png
  docs/images/GTEx-sample-annotations.png
  docs/images/GTEx-subject-annotations.png
  docs/images/KF-data-access.png
  docs/images/KF-select-biospecimen-id.png
  docs/images/KF-subset-list.png
  docs/images/KF-upload-ids.png
  docs/images/LINCS-data-portal.png
  docs/images/Metabolomics-download-data.png
  docs/images/Metabolomics-statistical-test.png
  docs/images/Metabolomics-workbench-summary.png
  docs/images/Neurodegeneration-ipsc-filter.png
  docs/images/Neurodegeneration-part-of-collection-ipsc.png
  docs/images/Neurodegeneration-stem-cell.png
  docs/images/dbGaP-data-source.png
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: Oct-2020, fixes, new

#244 first draft release update
  docs/Release-Notes/index.md
Labels: Oct-2020, new

#243 Fixing .pages tutorial titles + homepage revision
  docs/Bioinformatics-Skills/.pages
  docs/Bioinformatics-Skills/install_conda_tutorial.md
  docs/CFDE-Internal-Training/Website-Style-Guide/0index.md
  docs/Cheat-Sheets/.pages
  docs/Release-Notes/index.md
  docs/Web-Development/.pages
  docs/Web-Development/Javascript-dropdown-box-resources/.pages
  docs/Web-Development/Javascript-dropdown-box-resources/demo_javascript.md
  docs/Web-Development/Javascript-dropdown-box-resources/demo_javascript_rendered.md
  docs/Web-Development/Javascript-dropdown-box/.pages
  docs/Web-Development/index.md
  docs/Web-Development/javascript_chooser.md
  docs/images/CFDEwordcloud.png
  docs/index.md
Labels: Oct-2020, fixes

#248 Geographic location update and typos
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws3.md
Labels: Oct-2020, fixes

#247 Changes to CFDE Portal tutorial structure and explanation to overview pages of tutorials
  docs/Bioinformatics-Skills/.pages
  docs/Bioinformatics-Skills/CFDE-Portal/.pages
  docs/Bioinformatics-Skills/CFDE-Portal/index.md
  docs/Bioinformatics-Skills/index.md
  docs/CFDE-Internal-Training/Website-Style-Guide/1WebsiteNavStyle.md
  docs/CFDE-Internal-Training/index.md
  docs/Cheat-Sheets/index.md
  docs/Web-Development/index.md
  docs/index.md
  mkdocs.yml
Labels: Oct-2020, fixes
