Repository nih-cfde/training-and-engagement, pull requests merged in 2020-09, with the labels that each got.

#149 snakemake formatting edits
  docs/Bioinformatics-Tutorials/Snakemake/.pages
  docs/Bioinformatics-Tutorials/Snakemake/index.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_0.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_1.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_2.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_3.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_4.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_5.md
  docs/Bioinformatics-Tutorials/index.md
  docs/General-Tutorials/install_conda_tutorial.md
  docs/Resources/bash_cheatsheet.md
  docs/Resources/conda_cheatsheet.md
  docs/Resources/index.md
  docs/Resources/snakemake_cheatsheet.md
Labels: Oct-2020

#138 Add MIME type tutorial in DCC specific tab
  .github/PULL_REQUEST_TEMPLATE.md
  docs/CF-Tutorials/.pages
  docs/CF-Tutorials/MIME-type/.pages
  docs/CF-Tutorials/MIME-type/Example_data_files.md
  docs/CF-Tutorials/MIME-type/Intro_MIME_type.md
  docs/CF-Tutorials/MIME-type/Multiple_file_MIME.md
  docs/CF-Tutorials/MIME-type/Unexpected_behavior.md
  docs/CF-Tutorials/MIME-type/file.md
  docs/CF-Tutorials/MIME-type/index.md
  docs/CF-Tutorials/MIME-type/mime_supplementary_files/KF_File_ID.csv
  docs/CF-Tutorials/MIME-type/mime_supplementary_files/file_screencast.cast
  docs/CF-Tutorials/MIME-type/mime_supplementary_files/mimetype_screencast.cast
  docs/CF-Tutorials/MIME-type/mime_supplementary_files/siegfried_screencast.cast
  docs/CF-Tutorials/MIME-type/mime_supplementary_files/xdg-mime_screencast.cast
  docs/CF-Tutorials/MIME-type/mimetype.md
  docs/CF-Tutorials/MIME-type/siegfried.md
  docs/CF-Tutorials/MIME-type/xdg-utils.md
  docs/CF-Tutorials/index.md
  docs/Kids-First/Download_Data/index.md
  docs/images/KFDRC_file_ID_upload.png
  docs/images/KFDRC_search_by_file_ID.png
  docs/images/MIME_type_example_files.png
  docs/javascripts/asciinema-player.js
  docs/stylesheets/asciinema-player.css
  mkdocs.yml
Labels: Oct-2020

#151 added some more detail to introduction
  docs/General-Tutorials/install_conda_tutorial.md
Labels: Oct-2020, fixes

#167 Automated reviewer assignment and release drafter features
  .github/PULL_REQUEST_TEMPLATE.md
  .github/action-release-drafter.yml
  .github/actions/auto_assign_latest.yml
  .github/actions/auto_assign_stable.yml
  .github/workflows/action-auto-assign-latest.yml
  .github/workflows/action-auto-assign-stable.yml
  .github/workflows/release-drafter.yml
Labels: feature

#147 KF Tutorial Edits, reorganization and added data download tutorial
  docs/CF-Tutorials/MIME-type/Example_data_files.md
  docs/CF-Tutorials/MIME-type/index.md
  docs/Kids-First/.pages
  docs/Kids-First/Download_Data/.pages
  docs/Kids-First/Download_Data/Data-Download-Via-Cavatica.md
  docs/Kids-First/Download_Data/Data-Download-Via-KF-Portal.md
  docs/Kids-First/KF_7_PushToCavatica.md
  docs/Kids-First/Portal-Setup-And-Permissions/.pages
  docs/Kids-First/Portal-Setup-And-Permissions/KF_1_Getting_Started.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_2_The_Setup.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_3_KF_Registration.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_4_Cavatica_Registration.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_5_ConnectingAccounts.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_6_AccessingData.md
  docs/Kids-First/Setting-up-your-KF-Portal-Permissions/.pages
  docs/Kids-First/Setting-up-your-KF-Portal-Permissions/KF_2_Registration.md
  docs/Kids-First/index.md
  docs/images/Data_Download_Cavatica_Download_Links.png
  docs/images/Data_Download_Cavatica_Download_Links_2.png
  docs/images/Data_Download_File_download_one_by_one.png
  docs/images/Data_Download_selecting_files_cavatica.png
Labels: Oct-2020, fixes, new

#199 Update conda tutorial format
  docs/General-Tutorials/install_conda_tutorial.md
Labels: Oct-2020, fixes

#197 Update snakemake tutorial format
  docs/Bioinformatics-Tutorials/Snakemake/index.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_0.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_1.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_2.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_3.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_4.md
  docs/Bioinformatics-Tutorials/Snakemake/snakemake_5.md
  docs/General-Tutorials/index.md
Labels: Oct-2020, fixes

#180 Release plan, update with new branch names and release notes
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/auto_assign_dev.yml
  .github/workflows/action-auto-assign-dev.yml
  .github/workflows/release-drafter.yml
  docs/.pages
  docs/Releases/.pages
  docs/Releases/index.md
  docs/TrainingRepoReleasePlan/.pages
  docs/TrainingRepoReleasePlan/TrainingRepo-Release-Plan.md
  docs/images/Training_review_process.png
Labels: fixes, new

#203 Fixing GitHub token
  .github/action-release-drafter.yml
  .github/workflows/action-auto-assign-dev.yml
  .github/workflows/release-drafter.yml
Labels: fixes

#204 Correction to token in GitHub action - necessary for alpha release
  .github/action-release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: fixes

#220 Update KF tutorial landing pg format
  docs/Kids-First/Advanced-KF-Portal-Queries/KF_11_JointQuery.md
  docs/Kids-First/Advanced-KF-Portal-Queries/KF_12_CheckingQueries.md
  docs/Kids-First/Download_Data/Data-Download-Via-Cavatica.md
  docs/Kids-First/Download_Data/Data-Download-Via-KF-Portal.md
  docs/Kids-First/Exploring-Data-in-the-KF-Portal/KF_5_Explore.md
  docs/Kids-First/Exploring-Data-in-the-KF-Portal/KF_6_Filtering.md
  docs/Kids-First/Exploring-Data-in-the-KF-Portal/KF_7_Plots.md
  docs/Kids-First/KF_7_PushToCavatica.md
  docs/Kids-First/Portal-Setup-And-Permissions/.pages
  docs/Kids-First/Portal-Setup-And-Permissions/KF_1_Getting_Started.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_2_The_Setup.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_3_KF_Registration.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_4_Cavatica_Registration.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_5_ConnectingAccounts.md
  docs/Kids-First/Portal-Setup-And-Permissions/KF_6_AccessingData.md
  docs/Kids-First/index.md
Labels: Oct-2020, fixes

#230 Adding landing pg info for Sphinx and Javascript tutorials
  docs/General-Tutorials/.pages
  docs/General-Tutorials/Javascript-dropdown-box/.pages
  docs/General-Tutorials/Javascript-dropdown-box/demo_javascript.md
  docs/General-Tutorials/Javascript-dropdown-box/demo_javascript_rendered.md
  docs/General-Tutorials/Javascript-dropdown-box/javascript_chooser.md
  docs/General-Tutorials/Sphinx_Tutorial.md
  docs/General-Tutorials/index.md
Labels: Oct-2020, fixes

#229 Learning objectives and pre-reqs added to protected branches tutorial and Jekyll tutorial
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/RStudio.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/analyze.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/aws_instance_setup.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/background.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/download_accessAWS.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/AWS_Connected.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/BMP.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/Final_Output.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/Missing_Rates.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/imiss.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/lmiss.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/publicDNS.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/images/vcftools.png
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/index.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/manhattan.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/plink_install.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/terminate_aws.md
  docs/Bioinformatics-Tutorials/GWAS-in-the-cloud/vcftools_install.md
  docs/General-Tutorials/Jekyll_Tutorial.md
  docs/General-Tutorials/ProtectedBranch_HowTo.md
  docs/General-Tutorials/index.md
  docs/Releases/index.md
  docs/images/GWAS_General_AWS_Connected.png
  docs/images/GWAS_General_AWS_Free_Tier.png
  docs/images/GWAS_General_AWS_Updates.png
  docs/images/GWAS_General_KeyPair.png
  docs/images/GWAS_General_Launch.png
  docs/images/GWAS_General_Terminate_AWS.png
  docs/images/GWAS_General_Ubuntu.png
  docs/images/GWAS_General_aws_connect_your_instance.png
  docs/images/GWAS_General_aws_instances_list.png
  docs/images/GWAS_General_aws_ohio.png
  docs/images/GWAS_General_aws_ohio_selection.png
  docs/images/GWAS_General_launching.png
  docs/images/GWAS_General_publicDNS.png
  docs/images/General_GWAS_coatColor_man.png
Labels: Oct-2020, fixes

#228 Fixes to landing page for MIME type and MkDocs tutorials: website style guide
  docs/CF-Tutorials/MIME-type/index.md
  docs/General-Tutorials/mkdocs.md
  docs/stylesheets/extra.css
Labels: Oct-2020, fixes
