Repository nih-cfde/training-and-engagement, pull requests merged in 2020-12, with the labels that each got.

#283 snakemake image reorg and style guide updates
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_binder_close.png
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_binder_download.png
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_binder_terminal.png
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_downloaddata.jpeg
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_nothingtobedone.jpeg
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_rule_error_msg.jpeg
  docs/Bioinformatics-Skills/Snakemake/images-snakemake/snakemake_twosteps.jpeg
  docs/Bioinformatics-Skills/Snakemake/snakemake_1.md
  docs/Bioinformatics-Skills/Snakemake/snakemake_2.md
  docs/Bioinformatics-Skills/Snakemake/snakemake_3.md
  docs/CFDE-Internal-Training/Website-Style-Guide/2GenTutorialStyle.md
  docs/CFDE-Internal-Training/Website-Style-Guide/3TutorialComponents.md
  docs/CFDE-Internal-Training/Website-Style-Guide/4RecordingStyleGuide.md
  docs/CFDE-Internal-Training/Website-Style-Guide/tutorial_template_docs/TutorialTemplate.md
Labels: Dec-2020, fixes

#286 update recording style guide
  docs/CFDE-Internal-Training/Website-Style-Guide/3TutorialComponents.md
  docs/CFDE-Internal-Training/Website-Style-Guide/4RecordingStyleGuide.md
Labels: Dec-2020, fixes

#290 add matomo analytics script to training site
  docs/templates/main.html
Labels: Dec-2020, feature

#261 Updated release plan with tagging information
  README.md
  docs/TrainingRepoReleasePlan/TrainingRepo-Release-Plan.md
Labels: Dec-2020, fixes

#285 Edits to KF Data Download Screencasts
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST2.md
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST4.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/Data-Download-Via-Cavatica.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/Data-Download-Via-KF-Portal.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/index.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/vidlets/1_screencast.cast
  docs/Bioinformatics-Skills/Kids-First/Download_Data/vidlets/2_screencast.cast
  docs/Bioinformatics-Skills/Kids-First/Upload_Data.md
  docs/Bioinformatics-Skills/Simulate_Illumina_Reads.md
  docs/Release-Notes/index.md
Labels: Dec-2020, fixes

#263 Two Tutorials Added: Simulating Illumina Reads and Uploading Data to Cavatica
  docs/.pages
  docs/Bioinformatics-Skills/.pages
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST1.md
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST2.md
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST3.md
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST4.md
  docs/Bioinformatics-Skills/CFDE-Portal/.pages
  docs/Bioinformatics-Skills/CFDE-Portal/index.md
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/aws_instance_setup.md
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/download_accessAWS.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws3.md
  docs/Bioinformatics-Skills/Kids-First/.pages
  docs/Bioinformatics-Skills/Kids-First/Download_Data/Data-Download-Via-Cavatica.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/Data-Download-Via-KF-Portal.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/index.md
  docs/Bioinformatics-Skills/Kids-First/Download_Data/vidlets/1_screencast.cast
  docs/Bioinformatics-Skills/Kids-First/Download_Data/vidlets/2_screencast.cast
  docs/Bioinformatics-Skills/Kids-First/Upload_Data.md
  docs/Bioinformatics-Skills/Kids-First/images/Columns_Selection.png
  docs/Bioinformatics-Skills/Kids-First/images/Edit_Metadata_Button.png
  docs/Bioinformatics-Skills/Kids-First/images/Files_Tab.png
  docs/Bioinformatics-Skills/Kids-First/images/Popup_Window.png
  docs/Bioinformatics-Skills/Kids-First/images/Select_Samples.png
  docs/Bioinformatics-Skills/Kids-First/index.md
  docs/Bioinformatics-Skills/Simulate_Illumina_Reads.md
  docs/Bioinformatics-Skills/index.md
  docs/Bioinformatics-Skills/install_conda_tutorial.md
  docs/Release-Notes/index.md
  docs/Web-Development/.pages
  docs/Web-Development/Javascript-dropdown-box/.pages
  docs/Web-Development/Javascript-dropdown-box/demo_javascript.md
  docs/Web-Development/Javascript-dropdown-box/demo_javascript_rendered.md
  docs/Web-Development/Javascript-dropdown-box/javascript_chooser.md
  docs/Web-Development/index.md
  docs/images/Simulated_Data_Fastqc.png
  docs/images/Simulated_Data_t2xlarge.png
  docs/images/Simulated_Data_t2xlarge_storage.png
Labels: Dec-2020, new

#291 Updates to KF portal tutorials: screenshots and text
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_10_AndOr.md
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_11_JointQuery.md
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_12_CheckingQueries.md
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_9_AdvancedQuery.md
  docs/Bioinformatics-Skills/Kids-First/Exploring-Data-in-the-KF-Portal/KF_5_Explore.md
  docs/Bioinformatics-Skills/Kids-First/Exploring-Data-in-the-KF-Portal/KF_6_Filtering.md
  docs/Bioinformatics-Skills/Kids-First/Exploring-Data-in-the-KF-Portal/KF_7_Plots.md
  docs/Bioinformatics-Skills/Kids-First/Portal-Setup-And-Permissions/KF_2_The_Setup.md
  docs/Bioinformatics-Skills/Kids-First/Portal-Setup-And-Permissions/KF_3_KF_Registration.md
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_13.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_14.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_15.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_18.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_19.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_20.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_21.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_22.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_23.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_24.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_25.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_26.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_27.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_28.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_29.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_30.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_31.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_32.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_33.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_34.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_35.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_36.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_37.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KidsFirstPortal_38.png
  docs/Bioinformatics-Skills/Kids-First/index.md
Labels: Dec-2020, fixes

#274 Updating cfde-bot tutorial
  docs/CFDE-Internal-Training/Website-Style-Guide/4RecordingStyleGuide.md
  docs/CFDE-Internal-Training/cfdebot_website_editing.md
  docs/CFDE-Internal-Training/images-cfdebot/github-branch-stable.png
  docs/CFDE-Internal-Training/images-cfdebot/github-new-branch.png
Labels: Dec-2020, fixes

#242 Revamp of home page look and addition of carousel feature
  custom/assets/homepg-images/1.png
  custom/assets/homepg-images/2.png
  custom/assets/homepg-images/3.png
  custom/assets/homepg-images/4.png
  custom/assets/homepg-images/5.png
  custom/assets/homepg-images/6.png
  custom/assets/homepg-images/7.png
  custom/assets/homepg-images/nih-cf-logo.jpeg
  custom/assets/stylesheets/main.min.css
  custom/assets/stylesheets/overrides.min.css
  custom/main.html
  custom/overrides/home.html
  custom/overrides/main.html
  custom/partials/footer.html
  custom/partials/header.html
  custom/partials/nav.html
  docs/Bioinformatics-Skills/Simulate_Illumina_Reads.md
  docs/Cheat-Sheets/snakemake_cheatsheet.md
  docs/images/CFDE-logo-white-outline.png
  docs/index.md
  docs/javascripts/cls.min.js
  docs/stylesheets/extra.css
  mkdocs.yml
Labels: Dec-2020, feature

#296 December 2020 Release Notes
  docs/Release-Notes/index.md
Labels: Dec-2020, fixes

#299 Added Oct 2020 release notes
  docs/Release-Notes/.pages
  docs/Release-Notes/October-2020.md
  docs/Release-Notes/index.md
Labels: Dec-2020, fixes
