Repository nih-cfde/training-and-engagement, pull requests merged in 2021-02, with the labels that each got.

#323 Testing nav render on mkdocs-material version changes
  custom/partials/nav.html
Labels: fixes

#325 update cfdebot tutorial and fix conda resources
  docs/Bioinformatics-Skills/Snakemake/snakemake_0.md
  docs/Bioinformatics-Skills/install_conda_tutorial.md
  docs/CFDE-Internal-Training/cfdebot_website_editing.md
  docs/Cheat-Sheets/conda_cheatsheet.md
Labels: Feb-2021, fixes

#336 Update and fixes to release notes workflow and release plan
  .github/action-release-drafter.yml
  docs/TrainingRepoReleasePlan/TrainingRepo-Release-Plan.md
Labels: Feb-2021, fixes

#308 KF portal save option lesson
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/.pages
  docs/Bioinformatics-Skills/Kids-First/Advanced-KF-Portal-Queries/KF_13_SavingQueries.md
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_saveset1.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_saveset2.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_saveset3.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_saveset4.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_saveset5.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_savevirtualstudy1.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_savevirtualstudy2.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_savevirtualstudy3.png
  docs/Bioinformatics-Skills/Kids-First/images-kf/KF_savevirtualstudy4.png
  docs/Bioinformatics-Skills/Kids-First/index.md
  mkdocs.yml
  requirements.txt
Labels: Feb-2021, Training-Release, new

#321 Updated AWS tutorial based on training expereince
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/.pages
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/Terminate.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_12.PNG
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_12.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_2.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_3.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_4.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_6.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_7.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_9.PNG
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_9.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/aws_launch.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/connect_1.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/connect_2.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/connect_3.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/connect_4.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/mobaxterm_1.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/mobaxterm_2.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/mobaxterm_3.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/mobaxterm_3_2.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws2.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws3.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws4.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws5.md
Labels: Feb-2021, Training-Release, fixes

#306 intro to GCP tutorial
  docs/Bioinformatics-Skills/.pages
  docs/Bioinformatics-Skills/Introduction-to-GCP/.pages
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp1.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp2.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp3.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp4.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_activatefreetrial.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_authorise_shell.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_authorise_shell2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billingaccountmember.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billingenable.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billingoverview.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billingsetup.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billingtab.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_billinrename.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_blastfiles.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_bootdisk.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_connect1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_console.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_createproject.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_createvm.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_gcshell.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_login.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_project1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_project2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_projectid.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_reconnect.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_shell1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_shell2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_storage1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_storage2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_storage3.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vm.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmGCS.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vm_runoptions.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vm_runoptions2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmconfig.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmconfig1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmconfig2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmconfig3.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmconfig4.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmssh.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmstop.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/gcp_vmterminal.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/sra_config1.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/sra_config2.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/sra_config3.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/sra_config4.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/gcp_images/sra_example_sample.png
  docs/Bioinformatics-Skills/Introduction-to-GCP/index.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/sratoolkit_config_steps.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/testfile.txt
  docs/Bioinformatics-Skills/index.md
  mkdocs.yml
Labels: Feb-2021, Training-Release, new

#334 AWS Screen Tutorial
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/.pages
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/images-aws/original_ssh_terminal.png
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws4.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws5.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws5_Screen.md
  docs/Cheat-Sheets/.pages
  docs/Cheat-Sheets/index.md
  docs/Cheat-Sheets/screen_cheatsheet.md
Labels: Feb-2021, Training-Release, new

#328 GWAS Tutorial Fixes: Updated AWS images to new experience
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/aws_instance_setup.md
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/download_accessAWS.md
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/images-gwas/GWAS_General_Terminate_AWS.png
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/images-gwas/GWAS_General_aws_connect_your_instance.png
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/images-gwas/GWAS_General_aws_instances_list.png
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/images-gwas/GWAS_General_publicDNS.png
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/terminate_aws.md
Labels: Feb-2021, Training-Release, fixes

#316 RNAseq on Cavatica tutorial
  docs/Bioinformatics-Skills/.pages
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/.pages
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/10_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/11_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/12_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/13_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/14_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/15_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/16_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/17_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/18_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/19_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/1_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/20_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/21_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/22_Cavatica.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/2_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/3_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/4_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/5_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/6_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/7_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/8_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/9_KFDRC.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-1.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-10.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-2.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-3.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-4.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-5.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-6.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-7.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-8.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-6-9.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-1.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-2.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-3.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-4.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-5.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-7-6.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-1.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-2.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-3.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-4.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-5.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-8-6.png
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-images/rna-seq-workflow.jpeg
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-supporting-docs/.Rapp.history
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-supporting-docs/Cancer_DGE_Analysis.R
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna-seq-supporting-docs/Cancer_DGE_Analysis_Automate.R
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_1.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_2.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_3.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_4.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_5.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_6.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_7.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_8.md
  docs/Bioinformatics-Skills/index.md
  mkdocs.yml
Labels: Feb-2021, Training-Release, new

#324 Fixes to home page aesthetics and update carousel content
  custom/assets/homepg-images/8.png
  custom/assets/homepg-images/9.png
  custom/assets/stylesheets/overrides.min.css
  custom/overrides/home.html
  custom/partials/nav.html
  requirements.txt
Labels: Feb-2021, Training-Release, fixes

#340 Feb 2021 release notes
  docs/Bioinformatics-Skills/BLAST-Command-Line/BLAST1.md
  docs/Bioinformatics-Skills/CFDE-Portal/index.md
  docs/Bioinformatics-Skills/GWAS-in-the-cloud/index.md
  docs/Bioinformatics-Skills/Introduction-to-GCP/index.md
  docs/Bioinformatics-Skills/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/Bioinformatics-Skills/Kids-First/index.md
  docs/Bioinformatics-Skills/RNAseq-on-Cavatica/rna_seq_1.md
  docs/Bioinformatics-Skills/Snakemake/index.md
  docs/CFDE-Internal-Training/MIME-type/index.md
  docs/CFDE-Internal-Training/Website-Style-Guide/0index.md
  docs/Release-Notes/.pages
  docs/Release-Notes/December-2020.md
  docs/Release-Notes/index.md
Labels: Feb-2021, Training-Release
