Repository nih-cfde/training-and-engagement, pull requests merged in 2021-11, with the labels that each got.

#475 Conda edits for JOSE paper
  docs/General-Tools/Introduction-to-Conda/conda2.md
Labels: TrainingSite, fixes

#479 Updated reviewer list for PRs
  .github/actions/auto_assign_dev.yml
  .github/actions/auto_assign_stable.yml
Labels: fixes

#478 Updates to AWS tutorial
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_1.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_2.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_3.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_5.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_6.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_7.md
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_8.md
  docs/CFDE-Internal-Training/MIME-type/Example_data_files.md
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_10.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_12.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_2.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_3.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_4.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_5.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_7.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_9.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/aws_launch.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/connect_3.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/images-aws/connect_4.png
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/introtoaws1.md
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/introtoaws3.md
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/introtoaws4.md
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/introtoaws5.md
  docs/Cloud-Platforms/Introduction_to_Amazon_Web_Services/introtoaws5_Screen.md
  mkdocs.yml
Labels: fixes, Training-Release
