Repository nih-cfde/training-and-engagement, pull requests merged in 2022-02, with the labels that each got.

#505 Adding IDG tutorials
  docs/Common-Fund-Tools/.pages
  docs/Common-Fund-Tools/IDG.md
  docs/Common-Fund-Tools/index.md
  docs/images/ARCHS4-YT-1.png
  docs/images/IDGPharosYT_1.png
  docs/images/IDGPharosYT_2.png
  docs/images/IDG_Logo.png
  docs/images/PrismExp-YT-1.png
  docs/images/drugcentralYT_1.png
  docs/images/drugshotYT_1.png
  docs/images/geneshot-YT-1.png
  docs/images/harmonizome-YT-1.png
  docs/images/idg_logo_vertical.png
  docs/images/kea3YT_1.png
  docs/images/tigaYT_1.png
  docs/images/tinx-YT-1.png
Labels: TrainingSite

#504 add Dec and Jan workshops
  custom/overrides/home.html
Labels: TrainingSite, feb-2022

#503 GTEx/CAVATICA RNA-Seq Training Documentation
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/.pages
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-01.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-02.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-03.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-04.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-05.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06-01-nih-consent.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06-02-gen3-authorize.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-07.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-08.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-09.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-10.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-11.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-12.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-13.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-14-AnVIL_transfer_ipynb.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-14.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-15.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-16.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-17.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-18.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-19.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-20.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-21.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_9.md
Labels: documentation, feb-2022

#511 spelling fixes
  hackmd/README.md
Labels: Training-Release, feb-2022

#512 more spelling fixes
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_9.md
Labels: Training-Release, feb-2022

#509 Feb 2022 release
  .github/actions/auto_assign_dev.yml
  .github/actions/auto_assign_stable.yml
  custom/overrides/home.html
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/.pages
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-01.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-02.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-03.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-04.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-05.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06-01-nih-consent.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06-02-gen3-authorize.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-06.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-07.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-08.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-09.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-10.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-11.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-12.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-13.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-14-AnVIL_transfer_ipynb.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-14.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-15.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-16.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-17.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-18.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-19.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-20.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna-seq-images/rna-seq-9-21.png
  docs/Bioinformatic-Analyses/RNAseq-on-Cavatica/rna_seq_9.md
  docs/Common-Fund-Tools/.pages
  docs/Common-Fund-Tools/IDG.md
  docs/Common-Fund-Tools/index.md
  docs/images/ARCHS4-YT-1.png
  docs/images/IDGPharosYT_1.png
  docs/images/IDGPharosYT_2.png
  docs/images/IDG_Logo.png
  docs/images/PrismExp-YT-1.png
  docs/images/drugcentralYT_1.png
  docs/images/drugshotYT_1.png
  docs/images/geneshot-YT-1.png
  docs/images/harmonizome-YT-1.png
  docs/images/idg_logo_vertical.png
  docs/images/kea3YT_1.png
  docs/images/tigaYT_1.png
  docs/images/tinx-YT-1.png
  hackmd/AWS.md
  hackmd/README.md
  hackmd/UNIX.md
Labels: Training-Release, feb-2022
